services:
  microservice:
    build: 
      context: ../ 
      dockerfile: ./infra/microservice/Dockerfile 
    environment:
      - ENVIRONMENT=PRODUCTION
    depends_on:
      - redis
    ports:
      - "4000:4000"
  redis:
    image: redis:7-alpine
    ports:
      - "6390:6379"  
    volumes:
      - redis-data:/data  
volumes:
  redis-data:
